name: IOPS-FHIR-Package-Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      githubrepo:
        default: "NHSDigital/NHSEngland-FHIR-ImplementationGuide"
      githubranch:
        default: "main"
      packagename: 
        default: "fhir.r4.ukcore.stu2"
      packageversion: 
        default: "1.1.3"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - run: echo  ${{ inputs.working_directory }}
      - run: echo  ${{ github.event.inputs.githubrepo }}
      - run: echo  ${{ github.event.inputs.githubranch }}
      - run: echo  ${{ github.event.inputs.packagename }}
      - run: echo  ${{ github.event.inputs.packageversion }}
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
     
      - name: Check out ${{github.event.inputs.githubrepo}}
        uses: actions/checkout@master
        with:
          repository: ${{github.event.inputs.githubrepo}}
          path: gitrepository
          ref: ${{ github.event.inputs.githubranch }}

      - name: Check out validation-service-fhir-r4
        uses: actions/checkout@master
        with:
          repository: NHSDigital/IOPS-FHIR-Validation-Service
          ref: main
          path: validation-service-fhir-r4
        
      - name: Install npm
        run: npm ci   
      
      # TODO Need to pass in ig name and version
      - name: Configure FHIR Validator
        run: cd validation && npm start
        env:
          CI: true
          ONTO_CLIENT_ID: ${{ secrets.ONTO_CLIENT_ID }}
          ONTO_CLIENT_SECRET: ${{ secrets.ONTO_CLIENT_SECRET }}
          PACKAGE_NAME: ${{github.event.inputs.packagename}}
          PACKAGE_VERSION: ${{github.event.inputs.packageversion}}
        
      - name: Build FHIR Validator
        run: cd validation-service-fhir-r4 && mvn clean package

      - name: Run FHIR Validator
        run: 
          nohup java -jar validation-service-fhir-r4/target/fhir-validator.jar --terminology.url=https://ontology.nhs.uk/production1/fhir --terminology.authorization.tokenUrl=https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token --terminology.authorization.clientId=${{ secrets.ONTO_CLIENT_ID }} --terminology.authorization.clientSecret=${{ secrets.ONTO_CLIENT_SECRET }} &
          sleep 60
        
      - name: Run Test
        run: npm test -- --source=gitrepository
        env:
          CI: true
          TEST_REPO: ${{github.event.inputs.githubrepo}}
          TEST_BRANCH: ${{github.event.inputs.githubranch}}
          PACKAGE_NAME: ${{github.event.inputs.packagename}}
          PACKAGE_VERSION: ${{github.event.inputs.packageversion}}
