name: IOPS-FHIR-Package-Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      githubrepo:
        default: "NHSDigital/NHSDigital-FHIR-ImplementationGuide"
      githubranch:
        default: "master"
      packagename: 
        default: "fhir.r4.ukcore.stu1"
      packageversion: 
        default: "1.0.0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - run: echo  ${{ inputs.working_directory }}
      - run: echo  ${{ github.event.inputs.githubrepo }}
      - run: echo  ${{ github.event.inputs.githubranch }}
      - run: echo  ${{ github.event.inputs.packagename }}
      - run: echo  ${{ github.event.inputs.packageversion }}
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
     
      - name: Check out ${{github.event.inputs.githubrepo}}
        uses: actions/checkout@master
        with:
          repository: ${{github.event.inputs.githubrepo}}
          path: gitrepository
          ref: ${{ github.event.inputs.githubranch }}

      - name: Check out validation-service-fhir-r4
        uses: actions/checkout@master
        with:
          repository: NHSDigital/validation-service-fhir-r4
          ref: main2
          path: validation-service-fhir-r4
        
      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry and requests
        run: pip install poetry requests

      - name: Install dependencies
        run: poetry install

      - name: Set SPEC_VERSION env var
        run: echo ::set-env name=SPEC_VERSION::$(poetry run python scripts/calculate_version.py)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install node
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-npm-packages-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install npm
        run: make install    
      
      # TODO Need to pass in ig name and version
      - name: Configure FHIR Validator
        run: make configure-validation
        env:
          CI: true
          ONTO_CLIENT_ID: ${{ secrets.ONTO_CLIENT_ID }}
          ONTO_CLIENT_SECRET: ${{ secrets.ONTO_CLIENT_SECRET }}
          PACKAGE_NAME: ${{github.event.inputs.packagename}}
          PACKAGE_VERSION: ${{github.event.inputs.packageversion}}
        
      - name: Build FHIR Validator
        run: cd validation-service-fhir-r4 && mvn clean package

      - name: Run FHIR Validator
        run: 
          nohup java -jar validation-service-fhir-r4/target/fhir-validator.jar --terminology.url=https://ontology.nhs.uk/production1/fhir --terminology.authorization.tokenUrl=https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token --terminology.authorization.clientId=${{ secrets.ONTO_CLIENT_ID }} --terminology.authorization.clientSecret=${{ secrets.ONTO_CLIENT_SECRET }} &
          sleep 60
        
      - name: Run Test
        run: make test-package
        env:
          CI: true
          TEST_REPO: ${{github.event.inputs.githubrepo}}
          TEST_BRANCH: ${{github.event.inputs.githubranch}}
          PACKAGE_NAME: ${{github.event.inputs.packagename}}
          PACKAGE_VERSION: ${{github.event.inputs.packageversion}}
